image: maven:3.8.4-openjdk-11-slim

stages:         
  - publish
  - deploy
  
docker-publish:
  image: docker
  stage: publish
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - main

docker-deploy:
  stage: deploy
  before_script:
    - apt-get clean
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh azureuser@ase-delivery.westeurope.cloudapp.azure.com "echo '$CI_REGISTRY_PASSWORD' | sudo docker login $CI_REGISTRY_IMAGE -u '$CI_REGISTRY_USER' --password-stdin; sudo docker-compose down; sudo docker image prune -f; sudo docker pull $CI_REGISTRY_IMAGE:latest; sudo docker-compose up -d"
  only:
    - main
